# Generated by Django 4.2.16 on 2024-10-16 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_alter_todo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Not Started', help_text='The status of the Todo item (choices: Not Started, In Progress, Completed)', max_length=20),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_name',
            field=models.CharField(help_text='The name of the Todo item (max 60 characters)', max_length=60),
        ),
    ]
